---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.environmentName }}
  namespace: openshift-gitops
spec:
  namespaceResourceBlacklist:
  - group: '*'
    kind: ResourceQuota
  - group: '*'
    kind: LimitRange
  - group: '*'
    kind: NetworkPolicy
  - group: '*'
    kind: StatefulSet
  destinations:
    - name: {{ .Values.environmentName }}
      namespace: {{ .Values.environmentName }}
      server: 'https://kubernetes.default.svc'
  sourceRepos:
     - {{ .Values.gitrepoName }} 
