---
kind: Namespace
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    kubernetes.io/metadata.name: {{ $.Values.nameSpace }}
    argocd.argoproj.io/managed-by: openshift-gitops
  name: {{ $.Values.nameSpace }}

