---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-by-default
  namespace: {{ $.Values.nameSpace }}
  labels:
    platform/owner: {{ $.Values.nameSpace }}
spec:
  podSelector: {}
  ingress: []

