---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: {{ $.Values.nameSpace }}
  labels:
    platform/owner: {{ $.Values.nameSpace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
