---
apiVersion: v1
data:
  {{ $.Values.dockerFile }} 
kind: Secret
metadata:
  name: registry-secret-{{ $.Values.nameSpace }}
  namespace: {{ $.Values.nameSpace }}-{{ . }}
  labels: 
    platform/owner: {{ $.Values.nameSpace }}
type: Opaque
{{- end }}
